package database

import (
	"encoding/json"
	"fmt"
	"log"

	"it-platform-server/models"
)

// SeedPermissionRules 初始化岗位权限数据
func SeedPermissionRules() {
	var count int64
	DB.Model(&models.PermissionRule{}).Count(&count)
	if count > 0 {
		fmt.Println("岗位权限数据已存在，跳过初始化")
		return
	}

	type roleItem struct {
		Name    string `json:"name"`
		Enabled bool   `json:"enabled"`
	}
	type systemRule struct {
		System string     `json:"system"`
		Roles  []roleItem `json:"roles"`
	}

	// 从Excel解析的完整数据：岗位名称 -> 对应22个系统的规则
	seedData := map[string][]systemRule{
		"IT管理员": {
			{"防火墙", []roleItem{{"系统管理员", true}, {"配置管理员", false}, {"API管理员", true}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", true}}},
			{"Windows域控", []roleItem{{"域管理员", true}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", true}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", true}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", true}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", true}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", true}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", true}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", true}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", true}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"IT配置管理员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", true}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", true}}},
			{"Windows域控", []roleItem{{"域管理员", true}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", true}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", true}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", true}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", true}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", true}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"IT日志审计员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", true}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", true}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", true}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", true}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", true}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", true}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"数据库管理员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", true}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"数据操作员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", true}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", true}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", true}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", true}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", true}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", true}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", true}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"个人化操作员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", true}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", true}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"品质操作员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", true}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"产业化开发工程师": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", true}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", true}}},
			{"Linux服务器", []roleItem{{"管理员", true}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", true}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", true}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", true}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"门禁管理员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", true}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", true}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"门禁操作员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", true}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", true}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"安保员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", true}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", true}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"人事": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", true}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"密钥经理": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", true}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", true}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", true}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", true}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", true}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", true}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"电信密钥操作人": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", true}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"金融密钥操作人": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", true}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", true}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"SM密钥操作人": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", true}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", true}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"SM分量导入员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", true}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", true}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"SM密钥日志审计员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", true}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", true}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"密钥持有人": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", true}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", true}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"研发配置管理员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", true}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", false}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", true}, {"普通用户", false}}},
		},
		"研发人员": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", true}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", true}}},
		},
		"SM运维经理": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", true}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", true}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", true}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", true}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", true}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"SM运维工程师": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", true}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", true}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", true}, {"操作员", true}, {"审批员", false}, {"日志审计员", true}}},
			{"RSPDP", []roleItem{{"配置管理员", true}, {"操作员", true}, {"审批员", false}, {"日志审计员", true}}},
			{"RSPSR", []roleItem{{"配置管理员", true}, {"操作员", true}, {"审批员", false}, {"日志审计员", true}}},
			{"RSPEIM", []roleItem{{"配置管理员", true}, {"操作员", true}, {"审批员", false}, {"日志审计员", true}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
		"客户": {
			{"防火墙", []roleItem{{"系统管理员", false}, {"配置管理员", false}, {"API管理员", false}}},
			{"VMWareESXI/VCSA", []roleItem{{"管理员", false}}},
			{"Windows域控", []roleItem{{"域管理员", false}, {"生产域用户", false}, {"IT域用户", false}, {"研发域用户", false}, {"SM域用户", false}}},
			{"Windows管理机", []roleItem{{"管理员", false}}},
			{"数据库", []roleItem{{"DBA", false}, {"服务用户", false}}},
			{"Linux服务器", []roleItem{{"管理员", false}}},
			{"EventlogAnalyzer", []roleItem{{"管理员", false}, {"审计员", false}}},
			{"FTP", []roleItem{{"普通用户", false}}},
			{"PatchManager", []roleItem{{"管理员", false}}},
			{"SFTP", []roleItem{{"普通用户", true}}},
			{"DMS", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据中心", false}, {"品质部", false}, {"个人化", false}}},
			{"UICC数据生成系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"数据操作员", false}}},
			{"PKI管理系统", []roleItem{{"系统管理员", false}, {"日志审计员", false}, {"密钥管理员", false}, {"数据操作员", false}}},
			{"Hexhome", []roleItem{{"系统管理员", false}, {"SO", false}, {"CH", false}, {"KO", false}}},
			{"金融KMS", []roleItem{{"系统管理员", false}, {"SO", false}, {"Keycustodian", false}}},
			{"RSPDpplus", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPDP", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPSR", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"RSPEIM", []roleItem{{"配置管理员", false}, {"操作员", false}, {"审批员", false}, {"日志审计员", false}}},
			{"SM-KMS", []roleItem{{"密钥操作员", false}, {"密钥审批员", false}, {"分量导入员", false}, {"日志审计员", false}}},
			{"门禁系统DAS", []roleItem{{"门禁管理员", false}, {"门禁操作员", false}, {"安保员", false}}},
			{"SVN", []roleItem{{"配置管理员", false}, {"普通用户", false}}},
		},
	}

	for i, posName := range []string{
		"IT管理员", "IT配置管理员", "IT日志审计员", "数据库管理员", "数据操作员",
		"个人化操作员", "品质操作员", "产业化开发工程师", "门禁管理员", "门禁操作员",
		"安保员", "人事", "密钥经理", "电信密钥操作人", "金融密钥操作人",
		"SM密钥操作人", "SM分量导入员", "SM密钥日志审计员", "密钥持有人",
		"研发配置管理员", "研发人员", "SM运维经理", "SM运维工程师", "客户",
	} {
		rulesJSON, _ := json.Marshal(seedData[posName])
		rule := models.PermissionRule{
			PositionName: posName,
			SortOrder:    i,
			RulesJSON:    string(rulesJSON),
		}
		if err := DB.Create(&rule).Error; err != nil {
			log.Printf("初始化岗位权限数据失败 [%s]: %v", posName, err)
		}
	}
	fmt.Println("岗位权限数据初始化完成")
}

// SeedChangeTypes 初始化变更类型数据
func SeedChangeTypes() {
	var count int64
	DB.Model(&models.ChangeType{}).Count(&count)
	if count > 0 {
		fmt.Println("变更类型数据已存在，跳过初始化")
		return
	}

	types := []models.ChangeType{
		{Name: "FW-IT", SortOrder: 1},
		{Name: "FW-PD", SortOrder: 2},
		{Name: "FW-SM", SortOrder: 3},
		{Name: "FW-RD", SortOrder: 4},
		{Name: "设备", SortOrder: 5},
		{Name: "其他", SortOrder: 6},
	}

	for _, t := range types {
		if err := DB.Create(&t).Error; err != nil {
			log.Printf("初始化变更类型失败 [%s]: %v", t.Name, err)
		}
	}
	fmt.Println("变更类型数据初始化完成")
}
