# 服务器配置
server:
  port: ":8080"
  jwt_secret: "ENC[QCq+GGLygNJ7b8Ydc57qD9PdRxB34Et/Bw1qyRcq45halhddRqL9zWO0LO1+lbLqOJ6x8j6oKL/fu3WfpJcGoMoOmh3XtIFHvNpegVzcK/UGEDRWOcYu7hW7cpj5ojpojJGq6gfYu9hctn5jdJZeo5tfC1TMGzLaMC0i1ebuJQAPmB263hRuFdw9BFLnZ1g8Viu90naNXh4g5jSkGzP4v5bAWA9um6GsySc6uR0zvfO49aXDz/PWuzZlu/+7qSfBUtMf5CjJFSzi3oNUkNgO4bRACdiP1mxm0Eq33Atd5OSreeFwuXMgqiN8O7eQRbE5uqDrN520uSXrXLPd5vW4Zg==]"
  gin_mode: "debug"  # debug | release | test
  access_token_expiry: 120    # accessToken有效期（分钟）
  refresh_token_expiry: 7     # refreshToken有效期（天）
  # TLS配置
  tls:
    enabled: true
    cert_path: "./certificate/server.crt"
    key_path: "./certificate/server.key"
  # 配置加密私钥路径（用于解密 config.yml 中的 ENC[] 加密字段）
  config-key: "./key/config-key.pem"

# 文档版本号（用于导出文件页脚显示）
document:
  # Logo图片路径（用于导出文件页头显示）
  logo_path: "./assets/logo.png"
  # 用户变更记录表页脚
  permission_document_version: "IT06-10.0"
  # 用户权限确认表/SFTP账号确认表页脚
  user_permission_document_version: "IT07-3.0"
  # 补丁更新记录表页脚
  asset_document_version: "IT9-2.0"
  # 系统加固检查表页脚
  system_hardening_document_version: "IT11-1.0" 

# 数据库配置
database:
  username: "it"
  password: "ENC[hrjhY7ErjLuSV8nPz1FQ8QoYMXT27KksfxRH168pp6Eg+BC4pq1W3VGIJeSbZm75m7IKP7ciB3zBNjw5UA0DBOFWRckT74V+m/GpYAP8QKwJeE7QeJfCzyySwsn9ZdXsxvk4o5tsLz/CoLBrZ686IcF4GNxSEOC9dZm46woVdP8XPfwhQUXapEvDR0zYt1CMjv+0EDVc5g8zp83gVZAE1dTCgDckYH6T8+9NI9VzQ4W9uygqCyrwMp9Db5VkDj/rx6y2dZcC+rN96biUfUUcs8ZCtgWwKBLc0ULCwv/eNWKMcLXWrkjoH2p12Bta0gcF1BiZ8As2xW6v8ToH3AqT4A==]"
  host: "10.60.254.127"
  port: "3306"
  dbname: "it_platform"

# 上传配置
upload:
  path: "./uploads"
  # 策略文件上传路径
  policy_path: "./uploads/policies"
  # 网络拓扑图上传路径
  topology_path: "./uploads/topologies"
  # 用户权限月度检查文件上传路径
  permission_monthly_check_path: "./uploads/permission_monthly_checks"
  # 第三方 quarterly 检查文件上传路径
  third_party_quarterly_check_path: "./uploads/third_party_quarterly_checks"
  # 用户权限变更文件上传路径
  permission_user_change_path: "./uploads/permission_user_changes"
  # 变更记录表模板文件上传路径
  change_record_template_path: "./uploads/change_record_templates"
  # 变更记录扫描件上传路径
  change_record_path: "./uploads/change_records"
  # 漏洞扫描报告上传路径
  vulnerability_scan_path: "./uploads/vulnerability_scans"
  # 系统加固检查表上传路径
  system_hardening_check_path: "./uploads/system_hardening_checks"
  # 渗透测试报告上传路径
  penetration_test_path: "./uploads/penetration_tests"
  # 防火墙检查报告上传路径
  firewall_check_path: "./uploads/firewall_checks"
  # 补丁更新合规性报表上传路径
  patch_update_path: "./uploads/patch_updates"
  # 备份申请表上传路径
  backup_path: "./uploads/backups"
  # 恢复还原记录上传路径
  backup_recovery_path: "./uploads/backup_recoveries"
  # 备份与恢复记录表模板上传路径
  backup_template_path: "./uploads/backup_templates"
  # 表单保管区上传路径
  form_vault_path: "./uploads/form_vault"
  # 表单保管区快照路径
  form_vault_snapshot_path: "./uploads/form_vault/snapshots"
  # IT指南媒体资源上传路径
  it_guide_media_path: "./uploads/it_guide_media"

# RSA 加密配置
rsa:
  private_key_path: "./certificate/rsa_private.pem"
  public_key_path: "./certificate/rsa_public.pem"

# LDAP 配置
ldap:
  server: "ldaps://10.60.254.252:636"
  base_dn: "dc=hot,dc=local"
  use_tls: true
  insecure: true
  user_filter: "(sAMAccountName=%s)"
  username: "ylw@hot.local"
  password: "ENC[g4onpHvNo1rwP42MNNqcDpAK9SOjTfLdW5XP82uAm7/P0LYgMw6nHsWYgbWkm3VvYG9acYNEo5oyMx/ckBc0l1bJs0uIr33FGmZlSlqT6lbCWZjNd2dlXdjJdh/3NkuFEcVpFLiEt6eWVlUo665A6/IPs760Hp/AjKtVJi0Vmrkxvsc64rqAKLMe9ATVlkpQ279CMIMzCKZHLmt3FpIkv6VX3B0mDVziDgCCdefu/RYLEe2AyOgnrPPNZFy08KQAezMNI2d2SEh1EV2RgfLtxQcT+gx49DbPsnkKxSx+BnpyYxvoxvvWQNZlyDvG3aSKfsMFJ4MsBEg+PwVtpvyOeg==]"
  security_group_dn: "CN=IT部,OU=IT部,OU=HOT,DC=hot,DC=local"
  cert_path: "./certificate/ca.crt"

# 密码本配置
password_vault:
  aes_key: "ENC[iox/LKoMo+w5Vw3XQCKhgOFM4JOc18wShUTMFreX9jWpsepoLWRHxXPI3gGMcxcKYuNpk81cqDjLAlyIbJuoQmaRH1Wo/Kfv+wzPDDxVhb9H+l7ClJxMDWWu3mHluzBxB6f86Z4skBpLPeMEaJ2aQ9CPPqWKsGAnEc8/GZU+rdWvyAG0sxwZzCG8PGIWnLiKURzimvO0dv/h+7lklHijMfcLLj1UIsEoPB7DX6K+lUisjmyA0UD0Ic/NOhdwulCN0twQHJOhFsqJ1+EGkl7ZPhbjweQc9Liti2dyaTn81EQkW+MYnNFTtX16zxPDUSpuiNMgH6KN8I6ZW3GIiDBaYA==]"
