# 服务器配置
server:
  port: ":8080"
  jwt_secret: "it-platform-secret-key-2024"
  gin_mode: "debug"  # debug | release | test
  access_token_expiry: 120    # accessToken有效期（分钟）
  refresh_token_expiry: 7     # refreshToken有效期（天）
  tls:
    enabled: true
    cert_path: "./certificate/server.crt"
    key_path: "./certificate/server.key"

# 文档版本号（用于导出文件页脚显示）
document:
  # Logo图片路径（用于导出文件页头显示）
  logo_path: "./assets/logo.png"
  # 用户变更记录表页脚
  permission_document_version: "IT06-10.0"
  # 用户权限确认表/SFTP账号确认表页脚
  user_permission_document_version: "IT07-3.0"
  # 补丁更新记录表页脚
  asset_document_version: "IT9-2.0"
  # 系统加固检查表页脚
  system_hardening_document_version: "IT11-1.0" 

# 数据库配置
database:
  username: "it"
  password: "a*999999"
  host: "10.60.254.127"
  port: "3306"
  dbname: "it_platform"

# 上传配置
upload:
  path: "./uploads"
  # 策略文件上传路径
  policy_path: "./uploads/policies"
  # 网络拓扑图上传路径
  topology_path: "./uploads/topologies"
  # 用户权限月度检查文件上传路径
  permission_monthly_check_path: "./uploads/permission_monthly_checks"
  # 第三方 quarterly 检查文件上传路径
  third_party_quarterly_check_path: "./uploads/third_party_quarterly_checks"
  # 用户权限变更文件上传路径
  permission_user_change_path: "./uploads/permission_user_changes"
  # 变更记录表模板文件上传路径
  change_record_template_path: "./uploads/change_record_templates"
  # 变更记录扫描件上传路径
  change_record_path: "./uploads/change_records"
  # 漏洞扫描报告上传路径
  vulnerability_scan_path: "./uploads/vulnerability_scans"
  # 系统加固检查表上传路径
  system_hardening_check_path: "./uploads/system_hardening_checks"
  # 渗透测试报告上传路径
  penetration_test_path: "./uploads/penetration_tests"
  # 防火墙检查报告上传路径
  firewall_check_path: "./uploads/firewall_checks"
  # 补丁更新合规性报表上传路径
  patch_update_path: "./uploads/patch_updates"
  # 备份申请表上传路径
  backup_path: "./uploads/backups"
  # 恢复还原记录上传路径
  backup_recovery_path: "./uploads/backup_recoveries"
  # 备份与恢复记录表模板上传路径
  backup_template_path: "./uploads/backup_templates"

# RSA 加密配置
rsa:
  private_key_path: "./certificate/rsa_private.pem"
  public_key_path: "./certificate/rsa_public.pem"

# LDAP 配置
ldap:
  server: "ldaps://10.60.254.252:636"
  base_dn: "dc=hot,dc=local"
  use_tls: true
  insecure: true
  user_filter: "(sAMAccountName=%s)"
  username: "ylw@hot.local"
  password: "!Qw2!Qw2!Qw2!Qw2"
  security_group_dn: "CN=IT部,OU=IT部,OU=HOT,DC=hot,DC=local"
  cert_path: "./certificate/ca.crt"
