# 服务器配置
server:
  port: ":8080"
  jwt_secret: "it-platform-secret-key-2024"

# 文档版本号（用于导出文件页脚显示）
document:
  # Logo图片路径（用于导出文件页头显示）
  logo_path: "./assets/logo.png"
  # 用户变更记录表页脚
  permission_document_version: "IT06-10.0"
  # 用户权限确认表/SFTP账号确认表页脚
  user_permission_document_version: "IT07-3.0"
  # 补丁更新记录表页脚
  asset_document_version: "IT9-2.0" 

# 数据库配置
database:
  username: "it"
  password: "a*999999"
  host: "10.60.254.127"
  port: "3306"
  dbname: "it_platform"

# 上传配置
upload:
  path: "./uploads"
  policy_path: "./uploads/policies"
  topology_path: "./uploads/topologies"
  check_history_path: "./uploads/check_history"
  max_size: 33554432  # 32MB

# RSA 加密配置
rsa:
  private_key_path: "./certificate/rsa_private.pem"
  public_key_path: "./certificate/rsa_public.pem"

# LDAP 配置
ldap:
  server: "ldaps://10.60.254.252:636"
  base_dn: "dc=hot,dc=local"
  use_tls: true
  insecure: true
  user_filter: "(sAMAccountName=%s)"
  username: "ylw@hot.local"
  password: "!Qw2!Qw2!Qw2!Qw2"
  security_group_dn: "CN=IT部,OU=IT部,OU=HOT,DC=hot,DC=local"
  cert_path: "./certificate/ca.crt"
